"""initial

Revision ID: fe8de391e2f7
Revises: 
Create Date: 2026-04-23 09:23:40.925024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe8de391e2f7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bon_de_commande',
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('date_document', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_table('devis',
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('date_document', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_table('facture',
    sa.Column('montant_ttc', sa.Float(), nullable=True),
    sa.Column('montant_ht', sa.Float(), nullable=True),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('date_document', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_table('token_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('expire_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('mot_de_passe_hash', sa.String(length=500), nullable=False),
    sa.Column('role', sa.Enum('admin', 'user', 'read', name='roleenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('table_cible', sa.String(length=50), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ocr_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('duree_ms', sa.Integer(), nullable=False),
    sa.Column('duree_ocr_ms', sa.Integer(), nullable=False),
    sa.Column('duree_extraction_ms', sa.Integer(), nullable=False),
    sa.Column('succes', sa.Boolean(), nullable=False),
    sa.Column('nb_champs_extraits', sa.Integer(), nullable=False),
    sa.Column('nb_champs_vides', sa.Integer(), nullable=False),
    sa.Column('taux_completude', sa.Float(), nullable=False),
    sa.Column('nom_fichier', sa.String(), nullable=False),
    sa.Column('type_document', sa.String(), nullable=False),
    sa.Column('type_mime', sa.String(), nullable=False),
    sa.Column('taille_fichier', sa.Integer(), nullable=False),
    sa.Column('nb_pages', sa.Integer(), nullable=False),
    sa.Column('resultat_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('officelicence',
    sa.Column('devis_id', sa.Integer(), nullable=True),
    sa.Column('bon_de_commande_id', sa.Integer(), nullable=True),
    sa.Column('facture_id', sa.Integer(), nullable=True),
    sa.Column('type_licence', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=500), nullable=False),
    sa.Column('date_achat', sa.Date(), nullable=False),
    sa.Column('fournisseur', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bon_de_commande_id'], ['bon_de_commande.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['devis_id'], ['devis.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['facture_id'], ['facture.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_officelicence_type_licence'), 'officelicence', ['type_licence'], unique=False)
    op.create_index(op.f('ix_officelicence_version'), 'officelicence', ['version'], unique=False)
    op.create_table('ordinateur',
    sa.Column('officelicence_id', sa.Integer(), nullable=True),
    sa.Column('devis_id', sa.Integer(), nullable=True),
    sa.Column('bon_de_commande_id', sa.Integer(), nullable=True),
    sa.Column('facture_id', sa.Integer(), nullable=True),
    sa.Column('ram', sa.String(length=50), nullable=True),
    sa.Column('os', sa.String(length=100), nullable=True),
    sa.Column('nom_reseau', sa.String(length=50), nullable=True),
    sa.Column('tag_chargeur', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('mac_ethernet', sa.String(length=17), nullable=True),
    sa.Column('mac_wifi', sa.String(length=17), nullable=True),
    sa.Column('clef_wifi', sa.Boolean(), nullable=True),
    sa.Column('lecteur_cd', sa.Boolean(), nullable=True),
    sa.Column('casque', sa.Boolean(), nullable=True),
    sa.Column('absolute_dell', sa.Boolean(), nullable=True),
    sa.Column('watt', sa.Integer(), nullable=True),
    sa.Column('proprietaire', sa.String(length=255), nullable=True),
    sa.Column('service', sa.String(length=255), nullable=True),
    sa.Column('batiment', sa.String(length=255), nullable=True),
    sa.Column('type_equipement', sa.String(length=255), nullable=True),
    sa.Column('tag', sa.String(length=50), nullable=True),
    sa.Column('marque', sa.String(length=255), nullable=True),
    sa.Column('fin_garantie', sa.Date(), nullable=True),
    sa.Column('date_achat', sa.Date(), nullable=False),
    sa.Column('fournisseur', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bon_de_commande_id'], ['bon_de_commande.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['devis_id'], ['devis.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['facture_id'], ['facture.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['officelicence_id'], ['officelicence.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_address'),
    sa.UniqueConstraint('mac_ethernet'),
    sa.UniqueConstraint('mac_wifi'),
    sa.UniqueConstraint('nom_reseau'),
    sa.UniqueConstraint('tag'),
    sa.UniqueConstraint('tag_chargeur')
    )
    op.create_index(op.f('ix_ordinateur_batiment'), 'ordinateur', ['batiment'], unique=False)
    op.create_index(op.f('ix_ordinateur_date_achat'), 'ordinateur', ['date_achat'], unique=False)
    op.create_index(op.f('ix_ordinateur_fin_garantie'), 'ordinateur', ['fin_garantie'], unique=False)
    op.create_index(op.f('ix_ordinateur_marque'), 'ordinateur', ['marque'], unique=False)
    op.create_index(op.f('ix_ordinateur_officelicence_id'), 'ordinateur', ['officelicence_id'], unique=False)
    op.create_index(op.f('ix_ordinateur_proprietaire'), 'ordinateur', ['proprietaire'], unique=False)
    op.create_index(op.f('ix_ordinateur_service'), 'ordinateur', ['service'], unique=False)
    op.create_index(op.f('ix_ordinateur_type_equipement'), 'ordinateur', ['type_equipement'], unique=False)
    op.create_table('agent',
    sa.Column('ordinateur_id', sa.Integer(), nullable=True),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('prenom', sa.String(length=255), nullable=False),
    sa.Column('service', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ordinateur_id'], ['ordinateur.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_email'), 'agent', ['email'], unique=True)
    op.create_index(op.f('ix_agent_nom'), 'agent', ['nom'], unique=False)
    op.create_index(op.f('ix_agent_prenom'), 'agent', ['prenom'], unique=False)
    op.create_index(op.f('ix_agent_service'), 'agent', ['service'], unique=False)
    op.create_table('ecran',
    sa.Column('ordinateur_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('devis_id', sa.Integer(), nullable=True),
    sa.Column('bon_de_commande_id', sa.Integer(), nullable=True),
    sa.Column('facture_id', sa.Integer(), nullable=True),
    sa.Column('taille', sa.String(length=255), nullable=True),
    sa.Column('slot', sa.Integer(), nullable=True),
    sa.Column('proprietaire', sa.String(length=255), nullable=True),
    sa.Column('service', sa.String(length=255), nullable=True),
    sa.Column('batiment', sa.String(length=255), nullable=True),
    sa.Column('type_equipement', sa.String(length=255), nullable=True),
    sa.Column('tag', sa.String(length=50), nullable=True),
    sa.Column('marque', sa.String(length=255), nullable=True),
    sa.Column('fin_garantie', sa.Date(), nullable=True),
    sa.Column('date_achat', sa.Date(), nullable=False),
    sa.Column('fournisseur', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('slot IS NULL OR (slot BETWEEN 1 AND 5)', name='ck_slot_1_5'),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['bon_de_commande_id'], ['bon_de_commande.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['devis_id'], ['devis.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['facture_id'], ['facture.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ordinateur_id'], ['ordinateur.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ordinateur_id', 'slot', name='uq_ecran_slot_per_pc'),
    sa.UniqueConstraint('tag')
    )
    op.create_index(op.f('ix_ecran_agent_id'), 'ecran', ['agent_id'], unique=False)
    op.create_index(op.f('ix_ecran_batiment'), 'ecran', ['batiment'], unique=False)
    op.create_index(op.f('ix_ecran_date_achat'), 'ecran', ['date_achat'], unique=False)
    op.create_index(op.f('ix_ecran_fin_garantie'), 'ecran', ['fin_garantie'], unique=False)
    op.create_index(op.f('ix_ecran_marque'), 'ecran', ['marque'], unique=False)
    op.create_index(op.f('ix_ecran_ordinateur_id'), 'ecran', ['ordinateur_id'], unique=False)
    op.create_index(op.f('ix_ecran_proprietaire'), 'ecran', ['proprietaire'], unique=False)
    op.create_index(op.f('ix_ecran_service'), 'ecran', ['service'], unique=False)
    op.create_index(op.f('ix_ecran_taille'), 'ecran', ['taille'], unique=False)
    op.create_index(op.f('ix_ecran_type_equipement'), 'ecran', ['type_equipement'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ecran_type_equipement'), table_name='ecran')
    op.drop_index(op.f('ix_ecran_taille'), table_name='ecran')
    op.drop_index(op.f('ix_ecran_service'), table_name='ecran')
    op.drop_index(op.f('ix_ecran_proprietaire'), table_name='ecran')
    op.drop_index(op.f('ix_ecran_ordinateur_id'), table_name='ecran')
    op.drop_index(op.f('ix_ecran_marque'), table_name='ecran')
    op.drop_index(op.f('ix_ecran_fin_garantie'), table_name='ecran')
    op.drop_index(op.f('ix_ecran_date_achat'), table_name='ecran')
    op.drop_index(op.f('ix_ecran_batiment'), table_name='ecran')
    op.drop_index(op.f('ix_ecran_agent_id'), table_name='ecran')
    op.drop_table('ecran')
    op.drop_index(op.f('ix_agent_service'), table_name='agent')
    op.drop_index(op.f('ix_agent_prenom'), table_name='agent')
    op.drop_index(op.f('ix_agent_nom'), table_name='agent')
    op.drop_index(op.f('ix_agent_email'), table_name='agent')
    op.drop_table('agent')
    op.drop_index(op.f('ix_ordinateur_type_equipement'), table_name='ordinateur')
    op.drop_index(op.f('ix_ordinateur_service'), table_name='ordinateur')
    op.drop_index(op.f('ix_ordinateur_proprietaire'), table_name='ordinateur')
    op.drop_index(op.f('ix_ordinateur_officelicence_id'), table_name='ordinateur')
    op.drop_index(op.f('ix_ordinateur_marque'), table_name='ordinateur')
    op.drop_index(op.f('ix_ordinateur_fin_garantie'), table_name='ordinateur')
    op.drop_index(op.f('ix_ordinateur_date_achat'), table_name='ordinateur')
    op.drop_index(op.f('ix_ordinateur_batiment'), table_name='ordinateur')
    op.drop_table('ordinateur')
    op.drop_index(op.f('ix_officelicence_version'), table_name='officelicence')
    op.drop_index(op.f('ix_officelicence_type_licence'), table_name='officelicence')
    op.drop_table('officelicence')
    op.drop_table('ocr_stats')
    op.drop_table('logs')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('token_blacklist')
    op.drop_table('facture')
    op.drop_table('devis')
    op.drop_table('bon_de_commande')
    # ### end Alembic commands ###
