"""drop_agent_prenom_column

Revision ID: 21ab16d4136d
Revises: 9c59647ecb6f
Create Date: 2026-05-07 11:38:14.135315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21ab16d4136d'
down_revision: Union[str, None] = '9c59647ecb6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_prenom'), table_name='agent')
    op.drop_column('agent', 'prenom')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('prenom', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_agent_prenom'), 'agent', ['prenom'], unique=False)
    # ### end Alembic commands ###
