"""drop_ordinateur_agent_id_unique

Revision ID: 319d2bfc4918
Revises: 21ab16d4136d
Create Date: 2026-05-07 11:40:36.339637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '319d2bfc4918'
down_revision: Union[str, None] = '21ab16d4136d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_ordinateur_agent_id'), 'ordinateur', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_ordinateur_agent_id'), 'ordinateur', ['agent_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
