"""initial migration

Revision ID: 657d16dc421c
Revises: 
Create Date: 2026-01-20 08:41:08.065513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '657d16dc421c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('office_licenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=500), nullable=False),
    sa.Column('achat', sa.Date(), nullable=True),
    sa.Column('numero_bc', sa.String(length=255), nullable=True),
    sa.Column('type_license', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_office_licenses_achat'), 'office_licenses', ['achat'], unique=False)
    op.create_index(op.f('ix_office_licenses_version'), 'office_licenses', ['version'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('ordinateurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('office_license_id', sa.Integer(), nullable=True),
    sa.Column('proprietaire', sa.String(length=255), nullable=True),
    sa.Column('service', sa.String(length=255), nullable=True),
    sa.Column('batiment', sa.String(length=255), nullable=True),
    sa.Column('type_pc', sa.String(length=255), nullable=False),
    sa.Column('marque', sa.String(length=255), nullable=False),
    sa.Column('fournisseur', sa.String(length=255), nullable=True),
    sa.Column('ram', sa.String(length=50), nullable=True),
    sa.Column('os', sa.String(length=100), nullable=True),
    sa.Column('numero_bc', sa.String(length=50), nullable=True),
    sa.Column('tag', sa.String(length=50), nullable=True),
    sa.Column('nom_reseau', sa.String(length=50), nullable=True),
    sa.Column('tag_chargeur', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('mac_ethernet', sa.String(length=17), nullable=True),
    sa.Column('mac_wifi', sa.String(length=17), nullable=True),
    sa.Column('clef_wifi', sa.Boolean(), nullable=True),
    sa.Column('lecteur_cd', sa.Boolean(), nullable=True),
    sa.Column('casque', sa.Boolean(), nullable=True),
    sa.Column('absolute_dell', sa.Boolean(), nullable=True),
    sa.Column('watt', sa.Integer(), nullable=True),
    sa.Column('fin_garantie', sa.Date(), nullable=True),
    sa.Column('achat', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['office_license_id'], ['office_licenses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_address'),
    sa.UniqueConstraint('mac_ethernet'),
    sa.UniqueConstraint('mac_wifi'),
    sa.UniqueConstraint('nom_reseau'),
    sa.UniqueConstraint('tag'),
    sa.UniqueConstraint('tag_chargeur')
    )
    op.create_index(op.f('ix_ordinateurs_achat'), 'ordinateurs', ['achat'], unique=False)
    op.create_index(op.f('ix_ordinateurs_batiment'), 'ordinateurs', ['batiment'], unique=False)
    op.create_index(op.f('ix_ordinateurs_fin_garantie'), 'ordinateurs', ['fin_garantie'], unique=False)
    op.create_index(op.f('ix_ordinateurs_marque'), 'ordinateurs', ['marque'], unique=False)
    op.create_index(op.f('ix_ordinateurs_office_license_id'), 'ordinateurs', ['office_license_id'], unique=False)
    op.create_index(op.f('ix_ordinateurs_proprietaire'), 'ordinateurs', ['proprietaire'], unique=False)
    op.create_index(op.f('ix_ordinateurs_service'), 'ordinateurs', ['service'], unique=False)
    op.create_index(op.f('ix_ordinateurs_type_pc'), 'ordinateurs', ['type_pc'], unique=False)
    op.create_index(op.f('ix_ordinateurs_user_id'), 'ordinateurs', ['user_id'], unique=False)
    op.create_table('ecrans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=255), nullable=False),
    sa.Column('taille', sa.String(length=255), nullable=True),
    sa.Column('marque', sa.String(length=255), nullable=True),
    sa.Column('modele', sa.String(length=500), nullable=True),
    sa.Column('fournisseur', sa.String(length=255), nullable=True),
    sa.Column('numero_bc', sa.String(length=255), nullable=True),
    sa.Column('fin_garantie', sa.Date(), nullable=True),
    sa.Column('achat', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ordinateur_id', sa.Integer(), nullable=True),
    sa.Column('slot', sa.Integer(), nullable=True),
    sa.CheckConstraint('slot IS NULL OR (slot BETWEEN 1 AND 5)', name='ck_slot_1_5'),
    sa.ForeignKeyConstraint(['ordinateur_id'], ['ordinateurs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ordinateur_id', 'slot', name='uq_ecran_slot_per_pc'),
    sa.UniqueConstraint('tag')
    )
    op.create_index(op.f('ix_ecrans_achat'), 'ecrans', ['achat'], unique=False)
    op.create_index(op.f('ix_ecrans_fin_garantie'), 'ecrans', ['fin_garantie'], unique=False)
    op.create_index(op.f('ix_ecrans_marque'), 'ecrans', ['marque'], unique=False)
    op.create_index(op.f('ix_ecrans_modele'), 'ecrans', ['modele'], unique=False)
    op.create_index(op.f('ix_ecrans_ordinateur_id'), 'ecrans', ['ordinateur_id'], unique=False)
    op.create_index(op.f('ix_ecrans_taille'), 'ecrans', ['taille'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ecrans_taille'), table_name='ecrans')
    op.drop_index(op.f('ix_ecrans_ordinateur_id'), table_name='ecrans')
    op.drop_index(op.f('ix_ecrans_modele'), table_name='ecrans')
    op.drop_index(op.f('ix_ecrans_marque'), table_name='ecrans')
    op.drop_index(op.f('ix_ecrans_fin_garantie'), table_name='ecrans')
    op.drop_index(op.f('ix_ecrans_achat'), table_name='ecrans')
    op.drop_table('ecrans')
    op.drop_index(op.f('ix_ordinateurs_user_id'), table_name='ordinateurs')
    op.drop_index(op.f('ix_ordinateurs_type_pc'), table_name='ordinateurs')
    op.drop_index(op.f('ix_ordinateurs_service'), table_name='ordinateurs')
    op.drop_index(op.f('ix_ordinateurs_proprietaire'), table_name='ordinateurs')
    op.drop_index(op.f('ix_ordinateurs_office_license_id'), table_name='ordinateurs')
    op.drop_index(op.f('ix_ordinateurs_marque'), table_name='ordinateurs')
    op.drop_index(op.f('ix_ordinateurs_fin_garantie'), table_name='ordinateurs')
    op.drop_index(op.f('ix_ordinateurs_batiment'), table_name='ordinateurs')
    op.drop_index(op.f('ix_ordinateurs_achat'), table_name='ordinateurs')
    op.drop_table('ordinateurs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_office_licenses_version'), table_name='office_licenses')
    op.drop_index(op.f('ix_office_licenses_achat'), table_name='office_licenses')
    op.drop_table('office_licenses')
    # ### end Alembic commands ###
