"""drop agent service column

Revision ID: 9c59647ecb6f
Revises: b0aa449cb9cc
Create Date: 2026-05-07 10:35:58.391441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c59647ecb6f'
down_revision: Union[str, None] = 'b0aa449cb9cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_service'), table_name='agent')
    op.drop_column('agent', 'service')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('service', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_agent_service'), 'agent', ['service'], unique=False)
    # ### end Alembic commands ###
