"""

Revision ID: b0aa449cb9cc
Revises: b2c3d4e5f6a7
Create Date: 2026-05-06 14:23:45.590309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0aa449cb9cc'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        sa.text('ALTER TABLE ecran ALTER COLUMN taille TYPE FLOAT USING (NULLIF(taille, \'\')::double precision)')
    )
    op.create_index(op.f('ix_office_licence_date_achat'), 'office_licence', ['date_achat'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_office_licence_date_achat'), table_name='office_licence')
    op.alter_column('ecran', 'taille',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
