"""tag_not_null_clef_not_null_unique

Revision ID: d1245b5eb0fb
Revises: c1d2e3f4a5b6
Create Date: 2026-05-18 07:24:56.740912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1245b5eb0fb'
down_revision: Union[str, None] = 'c1d2e3f4a5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Backfill NULL tags/clefs with a placeholder derived from the row id
    # so the NOT NULL constraints can be applied to existing data.
    op.execute("UPDATE ecran SET tag = 'ECR-' || id WHERE tag IS NULL")
    op.execute("UPDATE ordinateur SET tag = 'PC-' || id WHERE tag IS NULL")
    op.execute("UPDATE office_licence SET clef = 'CLEF-' || id WHERE clef IS NULL")

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ecran', 'tag',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('office_licence', 'clef',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'office_licence', ['clef'])
    op.alter_column('ordinateur', 'tag',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_index(op.f('ix_token_blacklist_token'), table_name='token_blacklist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_token_blacklist_token'), 'token_blacklist', ['token'], unique=False)
    op.alter_column('ordinateur', 'tag',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint(None, 'office_licence', type_='unique')
    op.alter_column('office_licence', 'clef',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('ecran', 'tag',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
