PAGINATION_LIMIT_MIN = 1
PAGINATION_LIMIT_MAX = 100
PAGINATION_LIMIT_DEFAULT = 100
PAGINATION_SKIP_DEFAULT = 0

MAX_NAME_LENGTH = 255
MAX_EMAIL_LENGTH = 255
MAX_STRING_LENGTH = 500

HTTP_404_DETAIL = "Resource not found"
HTTP_422_DETAIL = "Invalid data"
HTTP_500_DETAIL = "Internal server error"
